### PR TITLE
Add co-author nitrotol

### PR DESCRIPTION
**Pull request by nitrotol**

### CODE REVIEW

**Review by Dobrovolskyi — APPROVED** [review]

**Review by 2sergeydev — APPROVED** [review]

**Review by nitrotol — COMMENTED** [review]
Guys, please approve this ASAP

**Review by megavis — APPROVED** [review]

**Review by yupirex — APPROVED** [review]

**Review by vvvis — APPROVED** [review]
Аппрувед

**Comment by serhiiKalchenko** [comment]
all right!

**Review by serhiiKalchenko — APPROVED** [review]
All good!;)

**Review by eugene-dudko — APPROVED** [review]

**Comment by eugene-dudko** [comment]
👍

**Pull request merged**
